### PR TITLE
Chaning the target framework to netstardard 2.0

### PR DESCRIPTION
**Pull request by thunder860**
I'm currently using this project in a few of my applications.  Because this targets an older version of net core, I'm getting a ton of vulnerabilities in my static analysis tool.  I've updated the target to netstandard so it'll work for my net 3.1 and net 6 projects and resolve the vulnerabilities I'm seeing.

### CODE REVIEW

**Comment by ardalis** [comment]
Thanks!

**Comment by thunder860** [comment]
@ardalis would it be possible to get this version pushed to nuget?

**Comment by ardalis** [comment]
@thunder860 waiting on this now if you think you can help. Thanks!
https://github.com/ardalis/AspNetCoreStartupServices/issues/6

**Comment by thunder860** [comment]
@ardalis I'll take a look. Thanks for the direction!

**Pull request merged**
