### PR TITLE
Adding Github workflows for building, testing, and publishing to nuget

### PR DESCRIPTION
**Pull request by thunder860**

### CODE REVIEW

**Review by ardalis — APPROVED** [review]

**Comment by ardalis** [comment]
Awesome, thanks!

**Comment by ardalis** [comment]
I should just need to add my NUGET API KEY and it should work.

**Comment by ardalis** [comment]
Had to fix a few things but it's working and published!

**Comment by thunder860** [comment]
Awesome! Thank you!

**Pull request merged**
